### ISSUE TITLE
array<string> empty

### ISSUE THREAD

**Issue by rotten** [komamitsu/treasuredata_fdw#14]
It looks like the contents of the array<string> datatype in treasure data is not getting populated in a varchar[] array in postgresql.  

I can select the column, from my foreign table, but it comes up empty when I get the results back - even though I can see the data in the treasure data table.

**Comment by komamitsu** [comment]
Yeah. The current version doesn't support array types. I'll take care of the feature.

**Comment by komamitsu** [comment]
Fixed this issue at https://github.com/komamitsu/treasuredata_fdw/pull/17

**Comment by komamitsu** [comment]
@rotten I released 1.1.0 that includes this feature. It would be great if you try the new version.
