### ISSUE TITLE
install failure to PG11

### ISSUE THREAD

**Issue by mkmk** [komamitsu/treasuredata_fdw#52]
treasuredata_fdwをPostgreSQL11の環境でインストールを試すとエラーが発生します。
環境:CentOS7

エラー内容は下記です。
--
    Finished release [optimized] target(s) in 59.18s                                                                                                                                                        
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o treasuredata_fdw.o treasuredata_fdw.c
treasuredata_fdw.c: 関数 ‘treasuredataPlanFore 型 ‘Form_pg_attribute’ignModify’ 内:
treasuredata_fdw.c:1036:29: エラー: を型 ‘FormData_pg_attribute’ を使用して初期化時に互換性のない型です
    Form_pg_attribute attr = tupdesc->attrs[attnum - 1];
                             ^
In file included from treasuredata_fdw.c:43:0:
treasuredata_fdw.c: 関数 ‘treasuredataBeginForeignModify’ 内:
/usr/pgsql-11/include/server/utils/rel.h:434:36: エラー: 型 ‘Form_pg_attribute’ を型 ‘FormData_pg_attribute’ を使用して初期化時に互換性のない型です
 #define RelationGetDescr(relation) ((relation)->rd_att)
                                    ^
treasuredata_fdw.c:1229:29: 備考: in expansion of macro ‘RelationGetDescr’
    Form_pg_attribute attr = RelationGetDescr(rel)->attrs[attnum - 1];
                             ^
In file included from /usr/pgsql-11/include/server/postgres.h:46:0,
                 from treasuredata_fdw.c:16:
treasuredata_fdw.c: 関数 ‘conversion_error_callback’ 内:
treasuredata_fdw.c:2535:59: エラー: ‘->’ の無効な型の引数です (‘FormData_pg_attribute’ 型です)
              NameStr(tupdesc->attrs[errpos->cur_attno - 1]->attname),
                                                           ^
/usr/pgsql-11/include/server/c.h:576:25: 備考: in definition of macro ‘NameStr’
 #define NameStr(name) ((name).data)
                         ^
gmake: *** [treasuredata_fdw.o] エラー 1
ERROR: command returned 2: gmake PG_CONFIG=/usr/pgsql-11/bin/pg_config all

**Comment by yajirobee** [comment]
I'm handling this on #53.

**Comment by komamitsu** [comment]
https://github.com/komamitsu/treasuredata_fdw/pull/53 fixed this issue
